import './global.css';

export const metadata = {
  title: 'Welcome to nextjs-demo',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
